services:
  coreai-techspike-document-analysis-api:
    build:
      context: .
      target: production
    image: coreai-techspike-document-analysis-api
    container_name: coreai-techspike-document-analysis-api
    depends_on:
      - coreai-techspike-document-analysis-api-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: coreai-techspike-document-analysis-api-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      OPEN_AI_ENDPOINT: ${OPEN_AI_ENDPOINT}
      OPEN_AI_API_KEY: ${OPEN_AI_API_KEY}
      OPEN_AI_DEPLOYMENT_ID: ${OPEN_AI_DEPLOYMENT_ID}
      POSTGRES_DB: coreai_techspike_document_analysis
      POSTGRES_HOST: ${POSTGRES_HOST:-coreai-techspike-document-analysis-api-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}

  coreai-techspike-document-analysis-api-azurite:
    image: mcr.microsoft.com/azure-storage/azurite

  coreai-techspike-document-analysis-api-postgres:
    image: pgvector/pgvector:pg13
    environment:
      POSTGRES_DB: coreai_techspike_document_analysis
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
