version: '3.8'
# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  coreai-techspike-document-analysis-api:
    build:
      target: development
    image: coreai-techspike-document-analysis-api-development
    container_name: coreai-techspike-document-analysis-api-development
    ports:
      - "3001:3000"
      - "9230:9229"
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./scripts:/home/node/scripts
      - ./package.json:/home/node/package.json
    environment: 
      AZURE_STORAGE_USE_CONNECTION_STRING: ${AZURE_STORAGE_USE_CONNECTION_STRING:-true}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING:-DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://host.docker.internal:10000/devstoreaccount1;}
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT:-devstoreaccount1}
  
  coreai-techspike-document-analysis-api-postgres:
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  coreai-techspike-document-analysis-api-azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "${CORE_AI_DOCUMENTS_BLOB_PORT:-10000}:10000"
    volumes:
      - azurite_data:/data

volumes:
  postgres_data:
  azurite_data: